imagestore/imagestore_cms/urls.py
#!/usr/bin/env python
# vim:fileencoding=utf-8
from __future__ import unicode_literals
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('imagestore.urls', namespace='imagestore')),
]

imagestore/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from .views import AlbumListView, ImageListView, UpdateImage, UpdateAlbum, \
    CreateImage, CreateAlbum, DeleteImage, DeleteAlbum, ImageView, \
    ImageTagAutocompleteView

urlpatterns = [
    url(r'^$', AlbumListView.as_view(), name='index'),

    url(r'^album/add/$', CreateAlbum.as_view(), name='create-album'),
    url(r'^album/(?P<album_id>\d+)/$', ImageListView.as_view(), name='album'),
    url(r'^album/(?P<pk>\d+)/edit/$', UpdateAlbum.as_view(), name='update-album'),
    url(r'^album/(?P<pk>\d+)/delete/$', DeleteAlbum.as_view(), name='delete-album'),

    url(r'^tag/(?P<tag>[^/]+)/$', ImageListView.as_view(), name='tag'),

    url(r'^user/(?P<username>\w+)/albums/', AlbumListView.as_view(), name='user'),
    url(r'^user/(?P<username>\w+)/$', ImageListView.as_view(), name='user-images'),

    url(r'^upload/$', CreateImage.as_view(), name='upload'),

    url(r'^image/(?P<pk>\d+)/$', ImageView.as_view(), name='image'),
    url(r'^album/(?P<album_id>\d+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-album'),
    url(r'^tag/(?P<tag>[^/]+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-tag'),
    url(r'^image/(?P<pk>\d+)/delete/$', DeleteImage.as_view(), name='delete-image'),
    url(r'^image/(?P<pk>\d+)/update/$', UpdateImage.as_view(), name='update-image'),

    url(r'^tag-autocomplete/$', ImageTagAutocompleteView.as_view(), name='tag-autocomplete'),
]

imagestore/models/image.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import swapper
from django.utils.translation import ugettext_lazy as _
from .bases.image import BaseImage


class Image(BaseImage):
    class Meta(BaseImage.Meta):
        abstract = False
        app_label = 'imagestore'
        verbose_name = _('Image')
        verbose_name_plural = _('Images')
        swappable = swapper.swappable_setting('imagestore', 'Image')

imagestore/templates/imagestore/album_delete.html
{% extends "imagestore/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this album?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

imagestore/templates/imagestore/album_list.html
{% extends "imagestore/base.html" %}
{% load i18n %}
{% load thumbnail %}

{% block title %}
    {% if view_user %}
        {% trans "Albums for user" %} {{ view_user }}
    {% else %}
        {% trans "All albums" %}
    {% endif %}
{% endblock %}

{% block imagestore-breadcrumb %}
    <li>
        {% if view_user %}
            {% trans "Albums for user" %} {{ view_user }}
        {% else %}
            {% trans "All albums" %}
        {% endif %}
    </li>
{% endblock %}

{% block imagestore-info %}
    {% if view_user and IMAGESTORE_SHOW_USER %}
        {% with user=view_user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}
{% endblock %}

{% block imagestore-related %}
    {% include "imagestore/tag-cloud.html" %}
{% endblock %}

{% block content %}
    <h1>{% if view_user %}
        {% trans "Albums for user" %} {{ view_user }}
    {% else %}
        {% trans "All albums" %}
    {% endif %}</h1>
    {% include "imagestore/pagination.html" %}
    <div class='album-list'>
        {% for album in album_list %}
            {% if album.get_head  or album.user == request.user %}
            <div class='album'>
                <div class='album-head'>
                    <a href="{{ album.get_absolute_url }}">
                    {% if album.get_head %}
                        {% thumbnail album.get_head.image "150x150" crop='center' as album_head %}
                            <img class="preview" {% if album.name %} alt="{{ album.name }}" {% endif %} src="{{ album_head.url }}">
                        {% endthumbnail %}
                    {% else %}
                        [{% trans "Empty album" %}]
                    {% endif %}
                    <br>
                    <span class="album-name">{{ album.name }}</span>
                    {% if not view_user and IMAGESTORE_SHOW_USER %}
                        <br>
                        <span class="album-user">
                            {% trans "user" %}: {{ album.user }}
                        </span>
                    {% endif %}
                    </a>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% include "imagestore/pagination.html" %}
{% endblock %}

imagestore/templates/imagestore/base.html
{% extends IMAGESTORE_TEMPLATE|default:"base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block head %}
    {% if IMAGESTORE_LOAD_CSS %}
        <link rel="stylesheet" type="text/css" href="{% static 'imagestore/imagestore.css' %}" media="screen" />
    {% endif %}
{% endblock %}

{% block breadcrumb %}
    <ul class='breadcrumb'>
        {% if request.path != '/' %}
            <li><a href="/">{% trans "Home" %}</a> <span class="divider">/</span></li>
        {% endif %}
        {% if request.path != imagestore_index_url %}
            <li><a href="{{ imagestore_index_url }}">{% trans "Gallery" %}</a> <span class="divider">/</span></li>
        {% endif %}
        {% block imagestore-breadcrumb %}
    {% endblock %}
    </ul>
{% endblock %}

{% block content %}
{% endblock content %}

{% block content-related %}
        {% block imagestore-info %}
        {% endblock %}
        <div id="controls">
            <ul>
                {% if imagestore_perms.add_image or request.user.is_superuser %}
                    <li><a href={% url 'imagestore:upload' %}>{% trans "Upload image" %}</a></li>
                {% endif %}
                {% if imagestore_perms.add_album or request.user.is_superuser %}
                    <li><a href={% url 'imagestore:create-album' %}>{% trans "Create new album" %}</a></li>
                {% endif %}
                {% block controls %}
                {% endblock controls %}
            </ul>
        </div>
        {% block imagestore-related %}
        {% endblock %}
{% endblock %}

imagestore/templates/imagestore/image-href.html
{% if album %}
    {% url 'imagestore:image-album' album_id=album.id pk=image.id %}
{% else %}
    {% if tag %}
        {% url 'imagestore:image-tag' tag=tag pk=image.id %}
    {% else %}
        {{ image.get_absolute_url }}
    {% endif %}
{% endif %}

imagestore/templates/imagestore/image-list.html
{% load i18n %}
{% load thumbnail %}
{% load imagestore_tags %}

<div id="image-thumbnails">
    {% for image in image_list %}
        {% thumbnail image.image "120x120" crop="center" as im %}
            <a class="thumb" rel='gallery-image[ilist]' href="{{ image.image.url }}">
                <img class="preview" {% imagestore_alt image forloop.counter %} src="{{ im.url }}">
            </a>
            <a href="{% url '{{ image.get_absolute_url }}' %}">
                {% if image.title %}
                    <br><span class='image-title'>{{ image.title }}</span>
                {% else %}
                    {% trans 'Info' %}
                {% endif %}
            </a>
        {% endthumbnail %}
    {% endfor %}
    {% include "imagestore/pagination.html" %}
</div>

imagestore/templates/imagestore/image-scope.html
{% load i18n %}
{% if view_user %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-view-user'>{% endif %}
        {% trans "User" %}: {{ view_user }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}
{% if album %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-album'>{% endif %}
        {% trans "Album" %}: {{ album.name }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}
{% if tag %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-album'>{% endif %}
    {% trans "Tag" %}: {{ tag }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}

imagestore/templates/imagestore/image.html
{% extends "imagestore/base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load tagging_tags %}

{% block title %}
    {% trans "Image" %} - {{ image.title }}
{% endblock %}

{% block imagestore-breadcrumb %}
    {% if view_user and IMAGESTORE_SHOW_USER %}
        <li class='scope-view-user'><a href="{% url 'imagestore:user-images' username=view_user %}">{% trans "User" %}: {{ view_user }}</a> <span class="divider">/</span></li>
    {% endif %}
    {% if album %}
        <li class='scope-album'><a href="{{ album.get_absolute_url }}">{% trans "Album" %}: {{ album.name }}</a> <span class="divider">/</span></li>
    {% endif %}
    {% if tag %}
        <li class='scope-tag'><a href="{% url 'imagestore:tag' tag=tag %}">{% trans "Tag" %}: {{ tag }}</a> <span class="divider">/</span></li>
    {% endif %}
    <li>
        {% if image.title %}
            {{ image.title }}
        {% else %}
            {{ image.id }}
        {% endif %}
    </li>
{% endblock %}

{% block imagestore-info %}
    <div class='user-info'>
    {% if IMAGESTORE_SHOW_USER %}
        {% with user=image.user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}
    </div>
{% endblock %}

{% block content %}
        {% if image.title %}<h1>{{ image.title }}</h1>{% endif %}
        {% if album or tag or view_user %}
            <h2>
                    {% include "imagestore/image-scope.html" %}
            </h2>
        {% endif %}
        <div class="image-description">
            {{ image.description }}
        </div>
        <div id="image-view">
            <div class="navigation">
                {% if previous %} <a class="previous-link" href="
                {% with previous as image %}
                    {% include "imagestore/image-href.html" %}
                {% endwith %}
                ">← {% trans "previous image" %}</a> {% endif %}
                {% if next %} <a class="next-link" href="{% with next as image %}
                    {% include "imagestore/image-href.html" %}
                {% endwith %}">{% trans "next image" %} →</a> {% endif %}
            </div>
            {% thumbnail image.image "800x800" as full_im %}
                <img class="preview" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ full_im.url }}">
            {% endthumbnail %}
        </div>
{% endblock content %}

{% block controls %}
    {% if request.user == image.user or perms.imagestore.moderate_images %}
        <li><a href="{% url 'imagestore:update-image' image.id %}">{% trans "Edit info" %}</a></li>
        <li><a href="{% url 'imagestore:delete-image' image.id %}">{% trans "Delete image" %}</a></li>
    {% endif %}
{% endblock %}

{% block imagestore-related %}

     <div class="tagging">
            <h2>{% trans "Tags" %}</h2>
            {% tags_for_object image as itags %}
            {% for tag in itags %}
                <a href="{% url 'imagestore:tag' tag.name %}">{{ tag.name }}</a>
            {% endfor %}
     </div>
     {% if image.place %}
         <div class='place'>
            <h2>{% trans "Place" %}</h2>
            <a href="{{ image.place.get_absolute_url }}">{{ image.place.name }} →</a>
         </div>
     {% endif %}
{% endblock %}

imagestore/templates/imagestore/image_confirm_delete.html
{% extends "imagestore/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this image?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

imagestore/templates/imagestore/image_delete.html
{% extends "imagestore/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this image?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

imagestore/templates/imagestore/image_list.html
{% extends "imagestore/base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load imagestore_tags %}

{% block imagestore-breadcrumb %}
    {% with "li" as scope_tag %}
        {% include "imagestore/image-scope.html" %}
    {% endwith %}
{% endblock %}

{% block title %}
    {% include "imagestore/image-scope.html" %}
{% endblock %}

{% block imagestore-info %}
    {% if view_user and IMAGESTORE_SHOW_USER %}
        {% with user=view_user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}
    {% if album and IMAGESTORE_SHOW_USER %}
        {% with user=album.user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}

{% endblock %}


{% block controls %}
    {% if album %}
        {% if request.user == album.user or perms.imagestore.moderate_albums %}
            <li><a href='{% url 'imagestore:update-album' pk=album.pk %}'>{% trans "Edit album" %}</a></li>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <h1>
        {% include "imagestore/image-scope.html" %}
    </h1>
    {% include "imagestore/pagination.html" %}
    <div id="image-thumbnails">
        {% for image in image_list %}
            <div class='image-preview'>
            {% thumbnail image.image "120x120" crop="center" as im %}
                <a class="thumb" rel='gallery-image[ilist]' href="{{ image.image.url }}">
                    <img class="preview" {% imagestore_alt image forloop.counter %} src="{{ im.url }}">
                </a>
                <a href="{% include "imagestore/image-href.html" %}">
                    {% if image.title %}
                        <br><span class='image-title'>{{ image.title }}</span>
                    {% else %}
                        {% trans 'Info' %}
                    {% endif %}
                </a>
            {% endthumbnail %}
            </div>
        {% endfor %}
    </div>
    {% include "imagestore/pagination.html" %}
{% endblock %}

imagestore/templates/imagestore/pagination.html
{% load i18n %}

{% if is_paginated %}
    <div class="pagination">
        <ul>

            <li class="prev {% if not page_obj.has_previous %}disabled{% endif %}">
                <a href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" >← {% trans "previous page" %}</a>
            </li>
            {% for page in page_obj.pages %}
                {% if page %}
                    <li {% ifequal page page_obj.number %}class="disabled"{% endifequal %}>
                        <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="disabled">
                        ...
                    </li>
                {% endif %}
            {% endfor %}
            <li class="next {% if not page_obj.has_next %}disabled{% endif %}">
                <a href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" >{% trans "next page" %} →</a>
            </li>
        </ul>
    </div>
{% endif %}

imagestore/templates/imagestore/pphoto.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'prettyphoto/css/prettyPhoto.css' %}" type="text/css" media="screen" charset="utf-8" />
<script src="{% static 'prettyphoto/js/jquery.prettyPhoto.js' %}" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript" charset="utf-8">
    var prettyparams = {
        animation_speed: 'fast',
        slideshow: 3000,
        autoplay_slideshow: false,
        opacity: 0.7,
        show_title: true,
        allow_resize: true,
        default_width: 1000,
        default_height: 344,
        counter_separator_label: '/',
        theme: 'facebook',
        overlay_gallery: true,
        changepicturecallback: function() {$pp_overlay.css({'height':$(document).height()})},
        };
    $(function(){$("a[rel^='gallery-image']").prettyPhoto(prettyparams)});
</script>

imagestore/templates/imagestore/tag.html
{% extends "imagestore/base.html" %}

{% load i18n %}
{% load thumbnail %}

{% block title %}
    {% trans "Gallery" %} - {% trans "Tag" %}: {{ tag }}
{% endblock %}

{% block imagestore-breadcrumb %}
    <li>{% trans "Tag" %}: {{ tag }}</li>
{% endblock %}

{% block content %}
    <h1>{% trans "Tag" %} - {{ tag }}</h1>
    {% include "imagestore/image-list.html" %}
{% endblock content %}

{% block content-related %}
    {% include "imagestore/tag-cloud.html" %}
{% endblock %}

imagestore/templates/imagestore/user_info.html
{% load i18n %}
{% load thumbnail %}

{# if we can't get profile then return user model itself #}
{% with profile=user.get_profile|default_if_none:user %}
    <div class="user-info">
        <h2>{% trans "User" %}</h2>
        <div class="avatar">
            <a href="{{ profile.get_absolute_url }}">
                {% thumbnail profile.avatar "80x80" as avatar %}
                    <img src="{{ avatar.url }}" alt="avatar">
                {% empty %}
                {% endthumbnail %}
            </a>
        </div>
        <div class="user-name">
            <a href="{{ profile.get_absolute_url }}">
                {{ user }}
            </a>
        </div>
     </div>
{% endwith %}